### ISSUE TITLE
Postgresql backup

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/seabee-geonode-charts#13]
With corruption problems like #11, and slow performance with cloud sql. One option would be to add a https://pgbackrest.org/ sidecar to the postgresql statefulset and create a cronjob that calls the endpoint. More information can also be found [here](https://www.timescale.com/blog/how-i-learned-to-stop-worrying-and-love-postgresql-on-kubernetes-continuous-backup-restore-validation-on-timescale-forge/) although we can't run the operator

**Comment by knl88** [comment]
Another alternative would be https://github.com/wal-g/wal-g

**Comment by knl88** [comment]
Suggest that for simplicity we just create a cronjob running https://docs.geonode.org/en/master/intermediate/backup/index.html, this can be incorporated in the helm chart

**Comment by JamesSample** [comment]
We discussed this last week, @knl88 , but it looks like you've already fixed it? Great if so!

Is there anything else we need to consider regarding GeoNode backups?
